services:
  mysql:
    image: mysql:8.0
    container_name: newsfeed-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root1234
      MYSQL_DATABASE: newsfeed
      MYSQL_USER: user
      MYSQL_PASSWORD: pass1234
    ports:
      - "3306:3306"
    volumes: # only for local dev
      - ./data/db:/var/lib/mysql  # persist to ./data/db

  redis:
    image: redis:7.2
    container_name: newsfeed-redis
    restart: always
    ports:
      - "6379:6379"
    volumes: # only for local dev
      - ./data/redis:/data # persist to ./data/redis
    command: ["redis-server", "--appendonly", "yes"] # run with persist option

  zookeeper:
    image: bitnami/zookeeper:3.9
    container_name: newsfeed-zookeeper
    restart: unless-stopped
    ports:
      - "2181:2181"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes

  kafka:
    image: bitnami/kafka:3.8
    container_name: newsfeed-kafka
    restart: unless-stopped
    ports:
      - "9092:9092"
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9092
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper

  prometheus:
    image: prom/prometheus:latest
    container_name: newsfeed-prometheus
    volumes:
      - ./monitoring/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    restart: always

  grafana:
    image: grafana/grafana:latest
    container_name: newsfeed-grafana
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - ./monitoring/grafana/provisioning:/etc/grafana/provisioning
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
    restart: always
