// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.1
// source: internal/handler/proto/grpc/service.proto

package grpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UserData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            *int64                 `protobuf:"varint,1,req,name=id" json:"id,omitempty"`
	UserName      *string                `protobuf:"bytes,2,req,name=user_name,json=userName" json:"user_name,omitempty"`
	DisplayName   *string                `protobuf:"bytes,3,req,name=display_name,json=displayName" json:"display_name,omitempty"`
	Email         *string                `protobuf:"bytes,4,req,name=email" json:"email,omitempty"`
	Dob           *string                `protobuf:"bytes,5,req,name=dob" json:"dob,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserData) Reset() {
	*x = UserData{}
	mi := &file_internal_handler_proto_grpc_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserData) ProtoMessage() {}

func (x *UserData) ProtoReflect() protoreflect.Message {
	mi := &file_internal_handler_proto_grpc_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserData.ProtoReflect.Descriptor instead.
func (*UserData) Descriptor() ([]byte, []int) {
	return file_internal_handler_proto_grpc_service_proto_rawDescGZIP(), []int{0}
}

func (x *UserData) GetId() int64 {
	if x != nil && x.Id != nil {
		return *x.Id
	}
	return 0
}

func (x *UserData) GetUserName() string {
	if x != nil && x.UserName != nil {
		return *x.UserName
	}
	return ""
}

func (x *UserData) GetDisplayName() string {
	if x != nil && x.DisplayName != nil {
		return *x.DisplayName
	}
	return ""
}

func (x *UserData) GetEmail() string {
	if x != nil && x.Email != nil {
		return *x.Email
	}
	return ""
}

func (x *UserData) GetDob() string {
	if x != nil && x.Dob != nil {
		return *x.Dob
	}
	return ""
}

type FollowData struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Follower        *UserData              `protobuf:"bytes,1,opt,name=follower" json:"follower,omitempty"`
	Following       *UserData              `protobuf:"bytes,2,opt,name=following" json:"following,omitempty"`
	FollowTimestamp *int64                 `protobuf:"varint,3,req,name=follow_timestamp,json=followTimestamp" json:"follow_timestamp,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *FollowData) Reset() {
	*x = FollowData{}
	mi := &file_internal_handler_proto_grpc_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FollowData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FollowData) ProtoMessage() {}

func (x *FollowData) ProtoReflect() protoreflect.Message {
	mi := &file_internal_handler_proto_grpc_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FollowData.ProtoReflect.Descriptor instead.
func (*FollowData) Descriptor() ([]byte, []int) {
	return file_internal_handler_proto_grpc_service_proto_rawDescGZIP(), []int{1}
}

func (x *FollowData) GetFollower() *UserData {
	if x != nil {
		return x.Follower
	}
	return nil
}

func (x *FollowData) GetFollowing() *UserData {
	if x != nil {
		return x.Following
	}
	return nil
}

func (x *FollowData) GetFollowTimestamp() int64 {
	if x != nil && x.FollowTimestamp != nil {
		return *x.FollowTimestamp
	}
	return 0
}

type SignupRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserName      *string                `protobuf:"bytes,1,req,name=user_name,json=userName" json:"user_name,omitempty"`
	Password      *string                `protobuf:"bytes,2,req,name=password" json:"password,omitempty"`
	DisplayName   *string                `protobuf:"bytes,3,req,name=display_name,json=displayName" json:"display_name,omitempty"`
	Email         *string                `protobuf:"bytes,4,req,name=email" json:"email,omitempty"`
	Dob           *string                `protobuf:"bytes,5,req,name=dob" json:"dob,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SignupRequest) Reset() {
	*x = SignupRequest{}
	mi := &file_internal_handler_proto_grpc_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignupRequest) ProtoMessage() {}

func (x *SignupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_handler_proto_grpc_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignupRequest.ProtoReflect.Descriptor instead.
func (*SignupRequest) Descriptor() ([]byte, []int) {
	return file_internal_handler_proto_grpc_service_proto_rawDescGZIP(), []int{2}
}

func (x *SignupRequest) GetUserName() string {
	if x != nil && x.UserName != nil {
		return *x.UserName
	}
	return ""
}

func (x *SignupRequest) GetPassword() string {
	if x != nil && x.Password != nil {
		return *x.Password
	}
	return ""
}

func (x *SignupRequest) GetDisplayName() string {
	if x != nil && x.DisplayName != nil {
		return *x.DisplayName
	}
	return ""
}

func (x *SignupRequest) GetEmail() string {
	if x != nil && x.Email != nil {
		return *x.Email
	}
	return ""
}

func (x *SignupRequest) GetDob() string {
	if x != nil && x.Dob != nil {
		return *x.Dob
	}
	return ""
}

type SignupResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          *UserData              `protobuf:"bytes,1,req,name=user" json:"user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SignupResponse) Reset() {
	*x = SignupResponse{}
	mi := &file_internal_handler_proto_grpc_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignupResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignupResponse) ProtoMessage() {}

func (x *SignupResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_handler_proto_grpc_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignupResponse.ProtoReflect.Descriptor instead.
func (*SignupResponse) Descriptor() ([]byte, []int) {
	return file_internal_handler_proto_grpc_service_proto_rawDescGZIP(), []int{3}
}

func (x *SignupResponse) GetUser() *UserData {
	if x != nil {
		return x.User
	}
	return nil
}

type LoginRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserName      *string                `protobuf:"bytes,1,req,name=user_name,json=userName" json:"user_name,omitempty"`
	Password      *string                `protobuf:"bytes,2,req,name=password" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginRequest) Reset() {
	*x = LoginRequest{}
	mi := &file_internal_handler_proto_grpc_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginRequest) ProtoMessage() {}

func (x *LoginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_handler_proto_grpc_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginRequest.ProtoReflect.Descriptor instead.
func (*LoginRequest) Descriptor() ([]byte, []int) {
	return file_internal_handler_proto_grpc_service_proto_rawDescGZIP(), []int{4}
}

func (x *LoginRequest) GetUserName() string {
	if x != nil && x.UserName != nil {
		return *x.UserName
	}
	return ""
}

func (x *LoginRequest) GetPassword() string {
	if x != nil && x.Password != nil {
		return *x.Password
	}
	return ""
}

type LoginResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          *UserData              `protobuf:"bytes,1,req,name=user" json:"user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginResponse) Reset() {
	*x = LoginResponse{}
	mi := &file_internal_handler_proto_grpc_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginResponse) ProtoMessage() {}

func (x *LoginResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_handler_proto_grpc_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginResponse.ProtoReflect.Descriptor instead.
func (*LoginResponse) Descriptor() ([]byte, []int) {
	return file_internal_handler_proto_grpc_service_proto_rawDescGZIP(), []int{5}
}

func (x *LoginResponse) GetUser() *UserData {
	if x != nil {
		return x.User
	}
	return nil
}

type UserUserData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            *int64                 `protobuf:"varint,1,req,name=id" json:"id,omitempty"`
	FollowerId    *int64                 `protobuf:"varint,2,req,name=follower_id,json=followerId" json:"follower_id,omitempty"`
	FollowingId   *int64                 `protobuf:"varint,3,req,name=following_id,json=followingId" json:"following_id,omitempty"`
	FollowTs      *int64                 `protobuf:"varint,4,req,name=follow_ts,json=followTs" json:"follow_ts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserUserData) Reset() {
	*x = UserUserData{}
	mi := &file_internal_handler_proto_grpc_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserUserData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserUserData) ProtoMessage() {}

func (x *UserUserData) ProtoReflect() protoreflect.Message {
	mi := &file_internal_handler_proto_grpc_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserUserData.ProtoReflect.Descriptor instead.
func (*UserUserData) Descriptor() ([]byte, []int) {
	return file_internal_handler_proto_grpc_service_proto_rawDescGZIP(), []int{6}
}

func (x *UserUserData) GetId() int64 {
	if x != nil && x.Id != nil {
		return *x.Id
	}
	return 0
}

func (x *UserUserData) GetFollowerId() int64 {
	if x != nil && x.FollowerId != nil {
		return *x.FollowerId
	}
	return 0
}

func (x *UserUserData) GetFollowingId() int64 {
	if x != nil && x.FollowingId != nil {
		return *x.FollowingId
	}
	return 0
}

func (x *UserUserData) GetFollowTs() int64 {
	if x != nil && x.FollowTs != nil {
		return *x.FollowTs
	}
	return 0
}

type FollowRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        *int64                 `protobuf:"varint,1,req,name=user_id,json=userId" json:"user_id,omitempty"`
	PeerId        *int64                 `protobuf:"varint,2,req,name=peer_id,json=peerId" json:"peer_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FollowRequest) Reset() {
	*x = FollowRequest{}
	mi := &file_internal_handler_proto_grpc_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FollowRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FollowRequest) ProtoMessage() {}

func (x *FollowRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_handler_proto_grpc_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FollowRequest.ProtoReflect.Descriptor instead.
func (*FollowRequest) Descriptor() ([]byte, []int) {
	return file_internal_handler_proto_grpc_service_proto_rawDescGZIP(), []int{7}
}

func (x *FollowRequest) GetUserId() int64 {
	if x != nil && x.UserId != nil {
		return *x.UserId
	}
	return 0
}

func (x *FollowRequest) GetPeerId() int64 {
	if x != nil && x.PeerId != nil {
		return *x.PeerId
	}
	return 0
}

type FollowResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IsFollowed    *bool                  `protobuf:"varint,1,req,name=is_followed,json=isFollowed" json:"is_followed,omitempty"`
	Pair          *UserUserData          `protobuf:"bytes,2,req,name=pair" json:"pair,omitempty"`
	Following     *UserData              `protobuf:"bytes,3,req,name=following" json:"following,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FollowResponse) Reset() {
	*x = FollowResponse{}
	mi := &file_internal_handler_proto_grpc_service_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FollowResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FollowResponse) ProtoMessage() {}

func (x *FollowResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_handler_proto_grpc_service_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FollowResponse.ProtoReflect.Descriptor instead.
func (*FollowResponse) Descriptor() ([]byte, []int) {
	return file_internal_handler_proto_grpc_service_proto_rawDescGZIP(), []int{8}
}

func (x *FollowResponse) GetIsFollowed() bool {
	if x != nil && x.IsFollowed != nil {
		return *x.IsFollowed
	}
	return false
}

func (x *FollowResponse) GetPair() *UserUserData {
	if x != nil {
		return x.Pair
	}
	return nil
}

func (x *FollowResponse) GetFollowing() *UserData {
	if x != nil {
		return x.Following
	}
	return nil
}

type UnfollowRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        *int64                 `protobuf:"varint,1,req,name=user_id,json=userId" json:"user_id,omitempty"`
	PeerId        *int64                 `protobuf:"varint,2,req,name=peer_id,json=peerId" json:"peer_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnfollowRequest) Reset() {
	*x = UnfollowRequest{}
	mi := &file_internal_handler_proto_grpc_service_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnfollowRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnfollowRequest) ProtoMessage() {}

func (x *UnfollowRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_handler_proto_grpc_service_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnfollowRequest.ProtoReflect.Descriptor instead.
func (*UnfollowRequest) Descriptor() ([]byte, []int) {
	return file_internal_handler_proto_grpc_service_proto_rawDescGZIP(), []int{9}
}

func (x *UnfollowRequest) GetUserId() int64 {
	if x != nil && x.UserId != nil {
		return *x.UserId
	}
	return 0
}

func (x *UnfollowRequest) GetPeerId() int64 {
	if x != nil && x.PeerId != nil {
		return *x.PeerId
	}
	return 0
}

type UnfollowResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IsUnfollowed  *bool                  `protobuf:"varint,1,req,name=is_unfollowed,json=isUnfollowed" json:"is_unfollowed,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnfollowResponse) Reset() {
	*x = UnfollowResponse{}
	mi := &file_internal_handler_proto_grpc_service_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnfollowResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnfollowResponse) ProtoMessage() {}

func (x *UnfollowResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_handler_proto_grpc_service_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnfollowResponse.ProtoReflect.Descriptor instead.
func (*UnfollowResponse) Descriptor() ([]byte, []int) {
	return file_internal_handler_proto_grpc_service_proto_rawDescGZIP(), []int{10}
}

func (x *UnfollowResponse) GetIsUnfollowed() bool {
	if x != nil && x.IsUnfollowed != nil {
		return *x.IsUnfollowed
	}
	return false
}

type FollowPaging struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LastValue     *int64                 `protobuf:"varint,1,req,name=last_value,json=lastValue" json:"last_value,omitempty"`
	Limit         *int64                 `protobuf:"varint,2,req,name=limit" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FollowPaging) Reset() {
	*x = FollowPaging{}
	mi := &file_internal_handler_proto_grpc_service_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FollowPaging) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FollowPaging) ProtoMessage() {}

func (x *FollowPaging) ProtoReflect() protoreflect.Message {
	mi := &file_internal_handler_proto_grpc_service_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FollowPaging.ProtoReflect.Descriptor instead.
func (*FollowPaging) Descriptor() ([]byte, []int) {
	return file_internal_handler_proto_grpc_service_proto_rawDescGZIP(), []int{11}
}

func (x *FollowPaging) GetLastValue() int64 {
	if x != nil && x.LastValue != nil {
		return *x.LastValue
	}
	return 0
}

func (x *FollowPaging) GetLimit() int64 {
	if x != nil && x.Limit != nil {
		return *x.Limit
	}
	return 0
}

type GetFollowersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        *int64                 `protobuf:"varint,1,req,name=user_id,json=userId" json:"user_id,omitempty"`
	Paging        *FollowPaging          `protobuf:"bytes,2,req,name=paging" json:"paging,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFollowersRequest) Reset() {
	*x = GetFollowersRequest{}
	mi := &file_internal_handler_proto_grpc_service_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFollowersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFollowersRequest) ProtoMessage() {}

func (x *GetFollowersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_handler_proto_grpc_service_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFollowersRequest.ProtoReflect.Descriptor instead.
func (*GetFollowersRequest) Descriptor() ([]byte, []int) {
	return file_internal_handler_proto_grpc_service_proto_rawDescGZIP(), []int{12}
}

func (x *GetFollowersRequest) GetUserId() int64 {
	if x != nil && x.UserId != nil {
		return *x.UserId
	}
	return 0
}

func (x *GetFollowersRequest) GetPaging() *FollowPaging {
	if x != nil {
		return x.Paging
	}
	return nil
}

type GetFollowersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Followers     []*FollowData          `protobuf:"bytes,1,rep,name=followers" json:"followers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFollowersResponse) Reset() {
	*x = GetFollowersResponse{}
	mi := &file_internal_handler_proto_grpc_service_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFollowersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFollowersResponse) ProtoMessage() {}

func (x *GetFollowersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_handler_proto_grpc_service_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFollowersResponse.ProtoReflect.Descriptor instead.
func (*GetFollowersResponse) Descriptor() ([]byte, []int) {
	return file_internal_handler_proto_grpc_service_proto_rawDescGZIP(), []int{13}
}

func (x *GetFollowersResponse) GetFollowers() []*FollowData {
	if x != nil {
		return x.Followers
	}
	return nil
}

type GetFollowingsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        *int64                 `protobuf:"varint,1,req,name=user_id,json=userId" json:"user_id,omitempty"`
	Paging        *FollowPaging          `protobuf:"bytes,2,req,name=paging" json:"paging,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFollowingsRequest) Reset() {
	*x = GetFollowingsRequest{}
	mi := &file_internal_handler_proto_grpc_service_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFollowingsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFollowingsRequest) ProtoMessage() {}

func (x *GetFollowingsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_handler_proto_grpc_service_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFollowingsRequest.ProtoReflect.Descriptor instead.
func (*GetFollowingsRequest) Descriptor() ([]byte, []int) {
	return file_internal_handler_proto_grpc_service_proto_rawDescGZIP(), []int{14}
}

func (x *GetFollowingsRequest) GetUserId() int64 {
	if x != nil && x.UserId != nil {
		return *x.UserId
	}
	return 0
}

func (x *GetFollowingsRequest) GetPaging() *FollowPaging {
	if x != nil {
		return x.Paging
	}
	return nil
}

type GetFollowingsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Followings    []*FollowData          `protobuf:"bytes,1,rep,name=followings" json:"followings,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFollowingsResponse) Reset() {
	*x = GetFollowingsResponse{}
	mi := &file_internal_handler_proto_grpc_service_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFollowingsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFollowingsResponse) ProtoMessage() {}

func (x *GetFollowingsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_handler_proto_grpc_service_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFollowingsResponse.ProtoReflect.Descriptor instead.
func (*GetFollowingsResponse) Descriptor() ([]byte, []int) {
	return file_internal_handler_proto_grpc_service_proto_rawDescGZIP(), []int{15}
}

func (x *GetFollowingsResponse) GetFollowings() []*FollowData {
	if x != nil {
		return x.Followings
	}
	return nil
}

type CreatePostRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreatePostRequest) Reset() {
	*x = CreatePostRequest{}
	mi := &file_internal_handler_proto_grpc_service_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePostRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePostRequest) ProtoMessage() {}

func (x *CreatePostRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_handler_proto_grpc_service_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePostRequest.ProtoReflect.Descriptor instead.
func (*CreatePostRequest) Descriptor() ([]byte, []int) {
	return file_internal_handler_proto_grpc_service_proto_rawDescGZIP(), []int{16}
}

type CreatePostResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreatePostResponse) Reset() {
	*x = CreatePostResponse{}
	mi := &file_internal_handler_proto_grpc_service_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePostResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePostResponse) ProtoMessage() {}

func (x *CreatePostResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_handler_proto_grpc_service_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePostResponse.ProtoReflect.Descriptor instead.
func (*CreatePostResponse) Descriptor() ([]byte, []int) {
	return file_internal_handler_proto_grpc_service_proto_rawDescGZIP(), []int{17}
}

type GetPostsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPostsRequest) Reset() {
	*x = GetPostsRequest{}
	mi := &file_internal_handler_proto_grpc_service_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPostsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPostsRequest) ProtoMessage() {}

func (x *GetPostsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_handler_proto_grpc_service_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPostsRequest.ProtoReflect.Descriptor instead.
func (*GetPostsRequest) Descriptor() ([]byte, []int) {
	return file_internal_handler_proto_grpc_service_proto_rawDescGZIP(), []int{18}
}

type GetPostsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPostsResponse) Reset() {
	*x = GetPostsResponse{}
	mi := &file_internal_handler_proto_grpc_service_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPostsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPostsResponse) ProtoMessage() {}

func (x *GetPostsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_handler_proto_grpc_service_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPostsResponse.ProtoReflect.Descriptor instead.
func (*GetPostsResponse) Descriptor() ([]byte, []int) {
	return file_internal_handler_proto_grpc_service_proto_rawDescGZIP(), []int{19}
}

type GetNewsfeedRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetNewsfeedRequest) Reset() {
	*x = GetNewsfeedRequest{}
	mi := &file_internal_handler_proto_grpc_service_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetNewsfeedRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetNewsfeedRequest) ProtoMessage() {}

func (x *GetNewsfeedRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_handler_proto_grpc_service_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetNewsfeedRequest.ProtoReflect.Descriptor instead.
func (*GetNewsfeedRequest) Descriptor() ([]byte, []int) {
	return file_internal_handler_proto_grpc_service_proto_rawDescGZIP(), []int{20}
}

type GetNewsfeedResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetNewsfeedResponse) Reset() {
	*x = GetNewsfeedResponse{}
	mi := &file_internal_handler_proto_grpc_service_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetNewsfeedResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetNewsfeedResponse) ProtoMessage() {}

func (x *GetNewsfeedResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_handler_proto_grpc_service_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetNewsfeedResponse.ProtoReflect.Descriptor instead.
func (*GetNewsfeedResponse) Descriptor() ([]byte, []int) {
	return file_internal_handler_proto_grpc_service_proto_rawDescGZIP(), []int{21}
}

var File_internal_handler_proto_grpc_service_proto protoreflect.FileDescriptor

const file_internal_handler_proto_grpc_service_proto_rawDesc = "" +
	"\n" +
	")internal/handler/proto/grpc/service.proto\x12\x04grpc\"\x82\x01\n" +
	"\bUserData\x12\x0e\n" +
	"\x02id\x18\x01 \x02(\x03R\x02id\x12\x1b\n" +
	"\tuser_name\x18\x02 \x02(\tR\buserName\x12!\n" +
	"\fdisplay_name\x18\x03 \x02(\tR\vdisplayName\x12\x14\n" +
	"\x05email\x18\x04 \x02(\tR\x05email\x12\x10\n" +
	"\x03dob\x18\x05 \x02(\tR\x03dob\"\x91\x01\n" +
	"\n" +
	"FollowData\x12*\n" +
	"\bfollower\x18\x01 \x01(\v2\x0e.grpc.UserDataR\bfollower\x12,\n" +
	"\tfollowing\x18\x02 \x01(\v2\x0e.grpc.UserDataR\tfollowing\x12)\n" +
	"\x10follow_timestamp\x18\x03 \x02(\x03R\x0ffollowTimestamp\"\x93\x01\n" +
	"\rSignupRequest\x12\x1b\n" +
	"\tuser_name\x18\x01 \x02(\tR\buserName\x12\x1a\n" +
	"\bpassword\x18\x02 \x02(\tR\bpassword\x12!\n" +
	"\fdisplay_name\x18\x03 \x02(\tR\vdisplayName\x12\x14\n" +
	"\x05email\x18\x04 \x02(\tR\x05email\x12\x10\n" +
	"\x03dob\x18\x05 \x02(\tR\x03dob\"4\n" +
	"\x0eSignupResponse\x12\"\n" +
	"\x04user\x18\x01 \x02(\v2\x0e.grpc.UserDataR\x04user\"G\n" +
	"\fLoginRequest\x12\x1b\n" +
	"\tuser_name\x18\x01 \x02(\tR\buserName\x12\x1a\n" +
	"\bpassword\x18\x02 \x02(\tR\bpassword\"3\n" +
	"\rLoginResponse\x12\"\n" +
	"\x04user\x18\x01 \x02(\v2\x0e.grpc.UserDataR\x04user\"\x7f\n" +
	"\fUserUserData\x12\x0e\n" +
	"\x02id\x18\x01 \x02(\x03R\x02id\x12\x1f\n" +
	"\vfollower_id\x18\x02 \x02(\x03R\n" +
	"followerId\x12!\n" +
	"\ffollowing_id\x18\x03 \x02(\x03R\vfollowingId\x12\x1b\n" +
	"\tfollow_ts\x18\x04 \x02(\x03R\bfollowTs\"A\n" +
	"\rFollowRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x02(\x03R\x06userId\x12\x17\n" +
	"\apeer_id\x18\x02 \x02(\x03R\x06peerId\"\x87\x01\n" +
	"\x0eFollowResponse\x12\x1f\n" +
	"\vis_followed\x18\x01 \x02(\bR\n" +
	"isFollowed\x12&\n" +
	"\x04pair\x18\x02 \x02(\v2\x12.grpc.UserUserDataR\x04pair\x12,\n" +
	"\tfollowing\x18\x03 \x02(\v2\x0e.grpc.UserDataR\tfollowing\"C\n" +
	"\x0fUnfollowRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x02(\x03R\x06userId\x12\x17\n" +
	"\apeer_id\x18\x02 \x02(\x03R\x06peerId\"7\n" +
	"\x10UnfollowResponse\x12#\n" +
	"\ris_unfollowed\x18\x01 \x02(\bR\fisUnfollowed\"C\n" +
	"\fFollowPaging\x12\x1d\n" +
	"\n" +
	"last_value\x18\x01 \x02(\x03R\tlastValue\x12\x14\n" +
	"\x05limit\x18\x02 \x02(\x03R\x05limit\"Z\n" +
	"\x13GetFollowersRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x02(\x03R\x06userId\x12*\n" +
	"\x06paging\x18\x02 \x02(\v2\x12.grpc.FollowPagingR\x06paging\"F\n" +
	"\x14GetFollowersResponse\x12.\n" +
	"\tfollowers\x18\x01 \x03(\v2\x10.grpc.FollowDataR\tfollowers\"[\n" +
	"\x14GetFollowingsRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x02(\x03R\x06userId\x12*\n" +
	"\x06paging\x18\x02 \x02(\v2\x12.grpc.FollowPagingR\x06paging\"I\n" +
	"\x15GetFollowingsResponse\x120\n" +
	"\n" +
	"followings\x18\x01 \x03(\v2\x10.grpc.FollowDataR\n" +
	"followings\"\x13\n" +
	"\x11CreatePostRequest\"\x14\n" +
	"\x12CreatePostResponse\"\x11\n" +
	"\x0fGetPostsRequest\"\x12\n" +
	"\x10GetPostsResponse\"\x14\n" +
	"\x12GetNewsfeedRequest\"\x15\n" +
	"\x13GetNewsfeedResponse2\xc3\x04\n" +
	"\aService\x125\n" +
	"\x06Signup\x12\x13.grpc.SignupRequest\x1a\x14.grpc.SignupResponse\"\x00\x122\n" +
	"\x05Login\x12\x12.grpc.LoginRequest\x1a\x13.grpc.LoginResponse\"\x00\x125\n" +
	"\x06Follow\x12\x13.grpc.FollowRequest\x1a\x14.grpc.FollowResponse\"\x00\x12;\n" +
	"\bUnfollow\x12\x15.grpc.UnfollowRequest\x1a\x16.grpc.UnfollowResponse\"\x00\x12G\n" +
	"\fGetFollowers\x12\x19.grpc.GetFollowersRequest\x1a\x1a.grpc.GetFollowersResponse\"\x00\x12J\n" +
	"\rGetFollowings\x12\x1a.grpc.GetFollowingsRequest\x1a\x1b.grpc.GetFollowingsResponse\"\x00\x12A\n" +
	"\n" +
	"CreatePost\x12\x17.grpc.CreatePostRequest\x1a\x18.grpc.CreatePostResponse\"\x00\x12;\n" +
	"\bGetPosts\x12\x15.grpc.GetPostsRequest\x1a\x16.grpc.GetPostsResponse\"\x00\x12D\n" +
	"\vGetNewsfeed\x12\x18.grpc.GetNewsfeedRequest\x1a\x19.grpc.GetNewsfeedResponse\"\x00B-Z+ep.k16/newsfeed/internal/handler/proto/grpc"

var (
	file_internal_handler_proto_grpc_service_proto_rawDescOnce sync.Once
	file_internal_handler_proto_grpc_service_proto_rawDescData []byte
)

func file_internal_handler_proto_grpc_service_proto_rawDescGZIP() []byte {
	file_internal_handler_proto_grpc_service_proto_rawDescOnce.Do(func() {
		file_internal_handler_proto_grpc_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_handler_proto_grpc_service_proto_rawDesc), len(file_internal_handler_proto_grpc_service_proto_rawDesc)))
	})
	return file_internal_handler_proto_grpc_service_proto_rawDescData
}

var file_internal_handler_proto_grpc_service_proto_msgTypes = make([]protoimpl.MessageInfo, 22)
var file_internal_handler_proto_grpc_service_proto_goTypes = []any{
	(*UserData)(nil),              // 0: grpc.UserData
	(*FollowData)(nil),            // 1: grpc.FollowData
	(*SignupRequest)(nil),         // 2: grpc.SignupRequest
	(*SignupResponse)(nil),        // 3: grpc.SignupResponse
	(*LoginRequest)(nil),          // 4: grpc.LoginRequest
	(*LoginResponse)(nil),         // 5: grpc.LoginResponse
	(*UserUserData)(nil),          // 6: grpc.UserUserData
	(*FollowRequest)(nil),         // 7: grpc.FollowRequest
	(*FollowResponse)(nil),        // 8: grpc.FollowResponse
	(*UnfollowRequest)(nil),       // 9: grpc.UnfollowRequest
	(*UnfollowResponse)(nil),      // 10: grpc.UnfollowResponse
	(*FollowPaging)(nil),          // 11: grpc.FollowPaging
	(*GetFollowersRequest)(nil),   // 12: grpc.GetFollowersRequest
	(*GetFollowersResponse)(nil),  // 13: grpc.GetFollowersResponse
	(*GetFollowingsRequest)(nil),  // 14: grpc.GetFollowingsRequest
	(*GetFollowingsResponse)(nil), // 15: grpc.GetFollowingsResponse
	(*CreatePostRequest)(nil),     // 16: grpc.CreatePostRequest
	(*CreatePostResponse)(nil),    // 17: grpc.CreatePostResponse
	(*GetPostsRequest)(nil),       // 18: grpc.GetPostsRequest
	(*GetPostsResponse)(nil),      // 19: grpc.GetPostsResponse
	(*GetNewsfeedRequest)(nil),    // 20: grpc.GetNewsfeedRequest
	(*GetNewsfeedResponse)(nil),   // 21: grpc.GetNewsfeedResponse
}
var file_internal_handler_proto_grpc_service_proto_depIdxs = []int32{
	0,  // 0: grpc.FollowData.follower:type_name -> grpc.UserData
	0,  // 1: grpc.FollowData.following:type_name -> grpc.UserData
	0,  // 2: grpc.SignupResponse.user:type_name -> grpc.UserData
	0,  // 3: grpc.LoginResponse.user:type_name -> grpc.UserData
	6,  // 4: grpc.FollowResponse.pair:type_name -> grpc.UserUserData
	0,  // 5: grpc.FollowResponse.following:type_name -> grpc.UserData
	11, // 6: grpc.GetFollowersRequest.paging:type_name -> grpc.FollowPaging
	1,  // 7: grpc.GetFollowersResponse.followers:type_name -> grpc.FollowData
	11, // 8: grpc.GetFollowingsRequest.paging:type_name -> grpc.FollowPaging
	1,  // 9: grpc.GetFollowingsResponse.followings:type_name -> grpc.FollowData
	2,  // 10: grpc.Service.Signup:input_type -> grpc.SignupRequest
	4,  // 11: grpc.Service.Login:input_type -> grpc.LoginRequest
	7,  // 12: grpc.Service.Follow:input_type -> grpc.FollowRequest
	9,  // 13: grpc.Service.Unfollow:input_type -> grpc.UnfollowRequest
	12, // 14: grpc.Service.GetFollowers:input_type -> grpc.GetFollowersRequest
	14, // 15: grpc.Service.GetFollowings:input_type -> grpc.GetFollowingsRequest
	16, // 16: grpc.Service.CreatePost:input_type -> grpc.CreatePostRequest
	18, // 17: grpc.Service.GetPosts:input_type -> grpc.GetPostsRequest
	20, // 18: grpc.Service.GetNewsfeed:input_type -> grpc.GetNewsfeedRequest
	3,  // 19: grpc.Service.Signup:output_type -> grpc.SignupResponse
	5,  // 20: grpc.Service.Login:output_type -> grpc.LoginResponse
	8,  // 21: grpc.Service.Follow:output_type -> grpc.FollowResponse
	10, // 22: grpc.Service.Unfollow:output_type -> grpc.UnfollowResponse
	13, // 23: grpc.Service.GetFollowers:output_type -> grpc.GetFollowersResponse
	15, // 24: grpc.Service.GetFollowings:output_type -> grpc.GetFollowingsResponse
	17, // 25: grpc.Service.CreatePost:output_type -> grpc.CreatePostResponse
	19, // 26: grpc.Service.GetPosts:output_type -> grpc.GetPostsResponse
	21, // 27: grpc.Service.GetNewsfeed:output_type -> grpc.GetNewsfeedResponse
	19, // [19:28] is the sub-list for method output_type
	10, // [10:19] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_internal_handler_proto_grpc_service_proto_init() }
func file_internal_handler_proto_grpc_service_proto_init() {
	if File_internal_handler_proto_grpc_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_handler_proto_grpc_service_proto_rawDesc), len(file_internal_handler_proto_grpc_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   22,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_handler_proto_grpc_service_proto_goTypes,
		DependencyIndexes: file_internal_handler_proto_grpc_service_proto_depIdxs,
		MessageInfos:      file_internal_handler_proto_grpc_service_proto_msgTypes,
	}.Build()
	File_internal_handler_proto_grpc_service_proto = out.File
	file_internal_handler_proto_grpc_service_proto_goTypes = nil
	file_internal_handler_proto_grpc_service_proto_depIdxs = nil
}
